# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-PT-Ords2Nums
version:      0.07
version_from: Ords2Nums.pm
installdirs:  site
requires:
    Lingua::PT::Words2Nums:        0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
